-- No se poblan las tablas de Partida, Jugador, Adqusiciones y JugadorActivo antes de configurar la partida
-- A continuación se hacen las inserciones para los datos del tablero y por defecto de la partida
-- Poblar Tabla TipoCasilla (Si es evento, salida, parada libre, propiedad, cárcel, movimiento o ir a la carcel)
INSERT INTO TIPOCASILLA(TipoID, TipoNombre) VALUES(1,'ParadaLibre');
INSERT INTO TIPOCASILLA(TipoID, TipoNombre) VALUES(2,'Evento');
INSERT INTO TIPOCASILLA(TipoID, TipoNombre) VALUES(3,'Propiedad');
INSERT INTO TIPOCASILLA(TipoID, TipoNombre) VALUES(4,'Movimiento');
INSERT INTO TIPOCASILLA(TipoID, TipoNombre) VALUES(5,'IrALaCarcel');

-- Poblar Tabla Casilla (Descripción detodas las casillas del tablero, considerando su tipo y posición)
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(1,'El Tunel (Salida)',1);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(2,'Básicas Viejo',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(3,'Evento1',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(4,'El italiano',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(5,'Básicas Nuevo',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(6,'Calle 45 - American Schoolway',4);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(7,'Arquidiseño',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(8,'Evento2',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(9,'Urapanes',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(10,'Carrizoza',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(11,'Carcel',1);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(12,'El 94',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(13,'Evento3',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(14,'Biblioteca Arrupe',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(15,'CFJD',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(16,'Avenida 39',4);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(17,'Giraldo',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(18,'Evento4',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(19,'El Mexicano',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(20,'Barón',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(21,'Cubos (Parada Libre)',1);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(22,'El 67',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(23,'Evento5',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(24,'La Estación',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(25,'HUSI',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(26,'SITP',4);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(27,'Artes',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(28,'Parque Nacional',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(29,'Evento6',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(30,'Centro Ático',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(31,'Capi (Ir a la Carcel)',5);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(32,'El Arca',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(33,'Il Posto',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(34,'Evento7',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(35,'Javeriana Estéreo',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(36,'Primera Línea del Metro',4);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(37,'Playita',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(38,'Atrio',3);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(39,'Evento8',2);
INSERT INTO CASILLA(PosicionTablero, NombreCasilla, TipoCasilla) VALUES(40,'Ingeniería',3);

-- Poblar Tabla GrupoPropiedades (Grupos de propiedades del mismo color en el tablero)
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(1,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(2,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(3,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(4,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(5,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(6,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(7,3);
INSERT INTO GRUPOPROPIEDADES(GrupoID, NumeroPropiedades) VALUES(8,3);

-- Poblar Tabla Propiedad (Propiedades en el juego, incluyendo el costo para comprarlas, y el valor de la renta por cada nivel, además del grupo de propiedades al que pertenece)
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(1,2,1,60,70,130,220,370,750);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(2,4,1,60,70,130,220,370,750);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(3,5,1,80,70,130,220,370,750);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(4,7,2,100,80,140,240,410,800);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(5,9,2,100,80,140,240,410,800);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(6,10,2,120,100,160,260,440,860);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(7,12,3,140,110,180,290,460,900);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(8,14,3,140,110,180,290,460,900);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(9,15,3,160,130,200,310,490,980);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(10,17,4,180,140,210,330,520,1000);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(11,19,4,180,140,210,330,520,1000);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(12,20,4,200,160,230,350,550,1100);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(13,22,5,220,170,250,380,580,1160);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(14,24,5,220,170,250,380,580,1160);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(15,25,5,240,190,270,400,610,1200);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(16,27,6,260,200,280,420,640,1300);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(17,28,6,260,200,280,420,640,1300);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(18,30,6,280,220,300,440,670,1340);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(19,32,7,300,230,320,460,700,1400);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(20,33,7,300,230,320,460,700,1400);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(21,35,7,320,250,340,480,730,1440);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(22,37,8,350,270,360,510,740,1500);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(23,38,8,350,270,360,510,740,1500);
INSERT INTO PROPIEDAD(PropiedadID, PosicionTablero, GrupoPropiedades, PrecioCompra, RentaNivel1, RentaNivel2, RentaNivel3, RentaNivel4, RentaNivel5) VALUES(24,40,8,400,300,400,560,810,1600);

-- Poblar Tabla TipoEvento (El mismo tipo de evento representa el mismo efecto sobre la base de datos) El nombre del evento representa el efecto que tiene
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(1,'PropiedadANivel5');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(2,'PropiedadANivel1');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(3,'PropiedadNivel-1');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(4,'PropiedadNivel+1');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(5,'Gana200');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(6,'Pierde50porPropiedad');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(7,'Gana50');
INSERT INTO TIPOEVENTO(TipoEventoID,TipoEvento) VALUES(8,'Gana100');

-- Poblar Tabla Evento (Descripciones-cartas de evento en el juego)
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Centro de Investigación Élite','Un filántropo dona equipos de última generación y tu edificio alcanza el máximo nivel. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Laboratorio Vanguardista','Tus instalaciones reciben certificación internacional y suben al nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Auditorio Emblemático','Se inaugura un espacio con tecnología punta y tu edificio se convierte en la joya del campus. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Beca de Innovación','Obtienes fondos para transformar tu bloque en referencia académica. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Renovación Magistral','Arquitectos diseñan un ambiente universitario de primer orden. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Patrocinio Empresarial','Una gran compañía equipa todo tu edificio con recursos premium. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Aula del Futuro','Tu propiedad estrena mobiliario y pantallas interactivas de última generación. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Laboratorio de Excelencia','Ganas un concurso nacional y tu laboratorio alcanza el estándar más alto. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Edificio Insignia','Se convierte en símbolo de la universidad: nivel 5 asegurado.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Milagro Académico','Gracias a alianzas y gestión brillante, tu edificio salta al máximo. Tu propiedad sube a nivel 5.',1);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Filtraciones en el Techo','Una falla obliga a cerrar áreas, dejando tu edificio en lo básico. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Equipos Obsoletos','Los aparatos se dañan y solo queda lo esencial funcionando. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Recorte Presupuestal','El presupuesto no alcanza, tu edificio se simplifica al nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Laboratorio en Pausa','Se retiran recursos por mantenimiento y baja su categoría. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Reforma Académica','Se reestructuran los espacios, pierdes todas las mejoras. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Estudiantes Inquietos','Una protesta obliga a cerrar pisos avanzados. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Obra Mal Planeada','Un error en planos obliga a volver al nivel inicial. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Sillas Rotas y Pizarras Viejas','Los salones pierden atractivo y caen al nivel básico. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Reparación Urgente','El edificio sufre daños y se limita a lo mínimo. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Desgaste Natural','El tiempo cobra factura y tu propiedad vuelve al origen. Tu propiedad baja a nivel 1.',2);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Aire Acondicionado Dañado','El mal clima te obliga a cerrar un piso. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Computadores Desactualizados','Un nivel queda inservible por equipos lentos. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Fugas en el Laboratorio','Una fuga química reduce la capacidad del edificio. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Menos Presupuesto de Investigación','Pierdes financiamiento, retrocedes un nivel.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Ascensor Fuera de Servicio','Cierras un piso hasta reparar el elevador. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Inspección Universitaria','Las normas de seguridad te hacen clausurar un área. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Caída en el Ranking','La reputación baja y con ella un nivel del edificio. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Clases Suspendidas','Menos actividad académica reduce el estatus. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Problemas Eléctricos','Pierdes un piso hasta instalar nuevo cableado. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Reducción de Aulas','Ajustas espacios y bajas un escalón. El nivel de tu propiedad disminuye en 1.',3);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Nueva Biblioteca','Agregas un ala de lectura y tu edificio crece. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Laboratorio Mejorado','Equipas un espacio con microscopios de última tecnología. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Café Estudiantil','Un rincón acogedor eleva la calidad del lugar. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Salón Multimedia','Instalas proyectores y pizarras digitales: +1 nivel.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Acreditación Académica','La certificación impulsa el valor del edificio. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Aula Maker','Añades un taller de innovación para los estudiantes. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Patrocinio de Exalumnos','Antiguos graduados financian mejoras. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Huerta Universitaria','Un toque verde eleva el prestigio del edificio. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Centro de Tutorías','Un nuevo servicio aumenta la utilidad del bloque. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Piso de Coworking','Espacios colaborativos enriquecen tu propiedad. El nivel de tu propiedad aumenta en 1.',4);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Subvención del Ministerio','Un proyecto académico obtiene fondos especiales. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Beca Institucional','Tu gestión te hace merecedor de un apoyo económico. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Donación de Exalumnos','Graduados aportan $200 para tus proyectos.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Premio a la Innovación Docente','Reconocen tus aportes con un cheque. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Venta de Publicaciones','Tus libros y papers generan ingresos. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Evento Universitario','Organizar una feria cultural te deja ganancias. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Congreso Internacional','Recibes honorarios por tu participación. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Rifa Académica','Tu número sale ganador en el sorteo del campus. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Patrocinio Privado','Una empresa financia parte de tu investigación. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Alquiler de Auditorios','Tus instalaciones producen ingresos extra. Ganas $200.',5);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Mantenimiento Semestral','Pintura, techos y limpieza cuestan $50 por bloque.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Revisión de Seguridad','Inspecciones oficiales generan gastos. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Reparación de Mobiliario','Cambiar sillas y mesas tiene su precio. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Actualización Tecnológica','Cada edificio necesita nuevos equipos. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Limpieza Profunda','Contratas personal extra para pulir tus espacios. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Control de Plagas en el Campus','Cuidar las zonas comunes cuesta $50 cada uno.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Certificación de Calidad','Cada propiedad paga por evaluaciones. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Seguro de Instalaciones','Proteges tus edificios ante accidentes. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Revisión Eléctrica','Los inspectores cobran por cada bloque. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Ajuste de Impuestos','El gobierno sube tasas universitarias. Pagas $50 por cada una de tus propiedades.',6);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Venta de Café','Tu cafetería gana $50 esta semana.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Fotocopias Populares','El centro de impresión del campus deja ganancias. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Reembolso de Materiales','Recuperas $50 por compras no usadas.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Taller de Fin de Semana','Dictas un curso rápido y obtienes $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Mercado de Libros Usados','Vendes textos de semestres pasados. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Tour Universitario','Cobras por mostrar el campus a visitantes. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Arriendo de Salones','Alquilas un aula para un evento. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Venta de Souvenirs','Camisetas y pines dejan ingresos. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Pequeña Donación','Un profesor invitado deja $50 para el fondo.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Campaña de Reciclaje','Recolectas materiales y obtienes ganancias. Ganas $50.',7);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Curso de Verano','Dictas un taller y ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Premio al Mejor Proyecto','Tus estudiantes te ayudan a obtener un cheque. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Venta de Entradas a un Evento','Organizar un concierto en el campus deja ingresos. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Campaña de Donaciones','La comunidad universitaria apoya tu trabajo. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Arriendo del Teatro','Cedes el auditorio para una obra. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Venta de Insignias','Souvenirs oficiales del campus generan $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Clase Magistral','Un público externo paga por asistir. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Convenio con Editorial','Publicas material académico con ganancias. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Exposición de Ciencia','La feria atrae patrocinadores. Ganas $100.',8);
INSERT INTO EVENTO(Nombre, Descripcion, TipoEvento) VALUES('Patrocinio Estudiantil','Un grupo de alumnos apoya tu edificio. Ganas $100.',8);

-- Poblar Tabla Icono (Se refiere al ícono que está usando el jugador para identificarse dentro del juego)
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(1,'Kiwi');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(2,'Balon');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(3,'Maleta');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(4,'Pescadito');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(5,'Carnet');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(6,'Ignacito');
INSERT INTO ICONO(IconoID, IconoNombre) VALUES(7,'Nave');