saves=/SQL/PartidasPasadas/
nuevaPartida.drop=/SQL/NuevaPartida/Drop.sql
nuevaPartida.ddl=/SQL/NuevaPartida/DDL.sql
nuevaPartida.inserts=/SQL/NuevaPartida/Insertions.sql

ModeloKiwi=/graphics/models/FichaEscala.glb
ModeloBalon=/graphics/models/FichaEscala.glb
ModeloMaleta=/graphics/models/FichaEscala.glb
ModeloPescadito=/graphics/models/FichaEscala.glb
ModeloCarnet=/graphics/models/FichaPlaceHolder.glb
ModeloIgnacito=/graphics/models/FichaPlaceHolder.glb
ModeloNave=/graphics/models/FichaPlaceHolder.glb