saves=/SQL/PartidasPasadas/
nuevaPartida.drop=/SQL/NuevaPartida/Drop.sql
nuevaPartida.ddl=/SQL/NuevaPartida/DDL.sql
nuevaPartida.inserts=/SQL/NuevaPartida/Insertions.sql

ModeloKiwi=/graphics/models/Fichas/Kiwi.glb
ModeloBalon=/graphics/models/Fichas/Balon.glb
ModeloMaleta=/graphics/models/Fichas/Maleta.glb
ModeloPescadito=/graphics/models/Fichas/Pescadito.glb
ModeloCarnet=/graphics/models/FichaEscala.glb
ModeloIgnacito=/graphics/models/FichaEscala.glb
ModeloNave=/graphics/models/FichaEscala.glb